<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<IsRoslynComponent>true</IsRoslynComponent>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>

		<!-- Vlastnosti NuGet balíčku -->
		<PackageId>AvaloniaConstructGenerator</PackageId>
		<Version>1.0.2</Version>
		<Authors>Zdendaki</Authors>
		<Description>Generates parameterless constructors for Avalonia windows for designer compatibility.</Description>
		<Tags>avalonia;roslyn;generator;sourcegenerator</Tags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/Zdendaki/AvaloniaConstructGenerator</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/Zdendaki/AvaloniaConstructGenerator</PackageProjectUrl>

		<!-- Zabrání vložení generátoru mezi běžné závislosti -->
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<!-- PrivateAssets="all" zamezí tomu, aby se tyto balíčky staly závislostí vašeho NuGetu -->
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
	</ItemGroup>

	<!-- Vložení zkompilované DLL do složky pro analyzátory uvnitř NuGet balíčku -->
	<ItemGroup>
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />

		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

</Project>