using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Linq;
using System.Text;

namespace AvaloniaConstructGenerator;

[Generator]
public class DesignerConstructorGenerator : IIncrementalGenerator
{
    private static readonly string[] TargetBaseTypes = ["Avalonia.Controls.Window", "Avalonia.Controls.UserControl", "Avalonia.Controls.Page"];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsPartialClass(s),
                transform: static (ctx, _) => GetTargetSymbol(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, static (spc, symbol) => Execute(spc, symbol!));
    }

    private static bool IsPartialClass(SyntaxNode node) => node is ClassDeclarationSyntax classDecl && classDecl.Modifiers.Any(SyntaxKind.PartialKeyword);

    private static INamedTypeSymbol? GetTargetSymbol(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol symbol)
            return null;

        // 1. Ověření, že třída NEMÁ explicitní bezparametrický konstruktor
        if (symbol.Constructors.Any(c => c.Parameters.Length == 0 && !c.IsImplicitlyDeclared))
            return null;

        // 2. Kontrola dědičnosti
        var baseType = symbol.BaseType;
        while (baseType != null)
        {
            if (Array.IndexOf(TargetBaseTypes, baseType.ToDisplayString()) >= 0)
                return symbol;

            baseType = baseType.BaseType;
        }

        return null;
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol classSymbol)
    {
        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : classSymbol.ContainingNamespace.ToDisplayString();

        var className = classSymbol.Name;

        var sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine("// <auto-generated/>");
        sourceBuilder.AppendLine("using System;");
        sourceBuilder.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sourceBuilder.AppendLine($"namespace {namespaceName}");
            sourceBuilder.AppendLine("{");
        }

        sourceBuilder.AppendLine($"    partial class {className}");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine("#pragma warning disable CS8618");
        sourceBuilder.AppendLine("        [Obsolete(\"For Avalonia Designer only\", true)]");
        sourceBuilder.AppendLine($"        public {className}() {{ }}");
        sourceBuilder.AppendLine("#pragma warning restore CS8618");
        sourceBuilder.AppendLine("    }");

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sourceBuilder.AppendLine("}");
        }

        var safeNamespace = string.IsNullOrEmpty(namespaceName) ? "Global" : namespaceName;
        context.AddSource($"{safeNamespace}.{className}.DesignerConstructor.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
    }
}
